import {
  capsuleH,
  capsuleV,
  closedPath,
  cornerLoops,
  enclosure,
  figureEightHorizontal,
  figureEightVertical,
  loopAround,
  moolaiSiluvai,
  pattern,
} from "./builders";
import type { KolamPattern } from "@/lib/game/types";

export const KOLAM_PATTERNS: KolamPattern[] = [
  pattern({
    id: "bindu",
    name: "Bindu",
    gridSize: 3,
    category: "beginner",
    difficulty: 1,
    tags: ["center", "loop", "first"],
    paths: [closedPath("p1", loopAround({ x: 1, y: 1 }))],
  }),
  pattern({
    id: "kambi",
    name: "Kambi",
    gridSize: 3,
    category: "beginner",
    difficulty: 1,
    tags: ["capsule", "row"],
    paths: [closedPath("p1", capsuleH(0, 1, 2))],
  }),
  pattern({
    id: "siluvai",
    name: "Siluvai",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["plus", "capsule", "overlap"],
    paths: [
      closedPath("h", capsuleH(0, 1, 2)),
      closedPath("v", capsuleV(1, 0, 2)),
    ],
  }),
  pattern({
    id: "moolai",
    name: "Moolai",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["corners", "loops"],
    paths: cornerLoops(3).map((points, i) => closedPath(`c${i + 1}`, points)),
  }),
  pattern({
    id: "kuttu",
    name: "Kuttu",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["enclosure", "2x2"],
    paths: [closedPath("p1", enclosure(0, 0, 1, 1))],
  }),
  pattern({
    id: "moolai-siluvai",
    name: "Moolai Siluvai",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["classic", "3x3", "corners", "plus"],
    paths: moolaiSiluvai(3).map((points, i) => closedPath(`p${i + 1}`, points)),
  }),
  pattern({
    id: "irani",
    name: "Irani",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["sikku", "figure-8"],
    paths: [closedPath("p1", figureEightHorizontal({ x: 0, y: 1 }))],
  }),
  pattern({
    id: "prakara",
    name: "Prakara",
    gridSize: 3,
    category: "beginner",
    difficulty: 2,
    tags: ["enclosure", "frame"],
    paths: [closedPath("p1", enclosure(0, 0, 2, 2))],
  }),
  pattern({
    id: "kambi-5",
    name: "Peru Kambi",
    gridSize: 5,
    category: "easy",
    difficulty: 2,
    tags: ["capsule"],
    paths: [closedPath("p1", capsuleH(0, 2, 4))],
  }),
  pattern({
    id: "siluvai-5",
    name: "Siluvai Five",
    gridSize: 5,
    category: "easy",
    difficulty: 2,
    tags: ["plus", "capsule"],
    paths: [
      closedPath("h", capsuleH(0, 2, 4)),
      closedPath("v", capsuleV(2, 0, 4)),
    ],
  }),
  pattern({
    id: "kuttu-5",
    name: "Kuttu Square",
    gridSize: 5,
    category: "easy",
    difficulty: 2,
    tags: ["enclosure"],
    paths: [closedPath("p1", enclosure(1, 1, 3, 3))],
  }),
  pattern({
    id: "moolai-siluvai-5",
    name: "Nava Plus",
    gridSize: 5,
    category: "easy",
    difficulty: 3,
    tags: ["classic", "corners", "plus"],
    paths: moolaiSiluvai(5).map((points, i) => closedPath(`p${i + 1}`, points)),
  }),
  pattern({
    id: "padi",
    name: "Padi",
    gridSize: 5,
    category: "easy",
    difficulty: 3,
    tags: ["nested", "enclosure"],
    paths: [
      closedPath("outer", enclosure(0, 0, 4, 4)),
      closedPath("inner", enclosure(1, 1, 3, 3)),
      closedPath("center", loopAround({ x: 2, y: 2 })),
    ],
  }),
  pattern({
    id: "malar-mini",
    name: "Malar Mini",
    gridSize: 5,
    category: "easy",
    difficulty: 3,
    tags: ["petals", "capsule"],
    paths: [
      closedPath("n", capsuleV(2, 0, 1)),
      closedPath("e", capsuleH(3, 2, 4)),
      closedPath("s", capsuleV(2, 3, 4)),
      closedPath("w", capsuleH(0, 2, 1)),
      closedPath("c", loopAround({ x: 2, y: 2 })),
    ],
  }),
  pattern({
    id: "maala",
    name: "Maala",
    gridSize: 5,
    category: "easy",
    difficulty: 3,
    tags: ["chain", "capsule"],
    paths: [
      closedPath("a", capsuleH(0, 2, 1)),
      closedPath("b", capsuleH(2, 2, 3)),
      closedPath("c", loopAround({ x: 4, y: 2 })),
    ],
  }),
  pattern({
    id: "kattam",
    name: "Kattam",
    gridSize: 5,
    category: "intermediate",
    difficulty: 3,
    tags: ["grid", "capsule", "overlap"],
    paths: [
      closedPath("r0", capsuleH(0, 0, 4)),
      closedPath("r2", capsuleH(0, 2, 4)),
      closedPath("r4", capsuleH(0, 4, 4)),
      closedPath("c0", capsuleV(0, 0, 4)),
      closedPath("c2", capsuleV(2, 0, 4)),
      closedPath("c4", capsuleV(4, 0, 4)),
    ],
  }),
  pattern({
    id: "nested",
    name: "Nested Kambi",
    gridSize: 5,
    category: "intermediate",
    difficulty: 3,
    tags: ["nested", "memory"],
    paths: [
      closedPath("outer", enclosure(0, 0, 4, 4)),
      closedPath("h", capsuleH(1, 2, 3)),
      closedPath("v", capsuleV(2, 1, 3)),
    ],
  }),
  pattern({
    id: "deepam",
    name: "Deepam",
    gridSize: 5,
    category: "intermediate",
    difficulty: 3,
    tags: ["plus", "sikku"],
    paths: [
      closedPath("h", figureEightHorizontal({ x: 1, y: 2 })),
      closedPath("v", figureEightVertical({ x: 2, y: 1 })),
    ],
  }),
  pattern({
    id: "malar",
    name: "Malar",
    gridSize: 5,
    category: "intermediate",
    difficulty: 3,
    tags: ["flower", "classic"],
    paths: moolaiSiluvai(5).map((points, i) => closedPath(`p${i + 1}`, points)),
  }),
  pattern({
    id: "poo",
    name: "Poo",
    gridSize: 7,
    category: "intermediate",
    difficulty: 3,
    tags: ["flower", "capsule"],
    paths: [
      closedPath("h", capsuleH(1, 3, 5)),
      closedPath("v", capsuleV(3, 1, 5)),
      closedPath("n", capsuleV(3, 0, 1)),
      closedPath("e", capsuleH(5, 3, 6)),
      closedPath("s", capsuleV(3, 5, 6)),
      closedPath("w", capsuleH(0, 3, 1)),
    ],
  }),
  pattern({
    id: "sikku-naalu",
    name: "Sikku Naalu",
    gridSize: 7,
    category: "intermediate",
    difficulty: 4,
    tags: ["sikku", "enclosure"],
    paths: [
      closedPath("box", enclosure(2, 2, 4, 4)),
      closedPath("eight", figureEightHorizontal({ x: 2, y: 3 })),
    ],
  }),
  pattern({
    id: "padi-7",
    name: "Perum Padi",
    gridSize: 7,
    category: "advanced",
    difficulty: 4,
    tags: ["nested", "enclosure"],
    paths: [
      closedPath("outer", enclosure(0, 0, 6, 6)),
      closedPath("mid", enclosure(1, 1, 5, 5)),
      closedPath("inner", enclosure(2, 2, 4, 4)),
      closedPath("center", loopAround({ x: 3, y: 3 })),
    ],
  }),
  pattern({
    id: "moolai-siluvai-7",
    name: "Moolai Siluvai Seven",
    gridSize: 7,
    category: "advanced",
    difficulty: 4,
    tags: ["classic", "plus", "corners"],
    paths: moolaiSiluvai(7).map((points, i) => closedPath(`p${i + 1}`, points)),
  }),
  pattern({
    id: "kattam-7",
    name: "Kattam Seven",
    gridSize: 7,
    category: "advanced",
    difficulty: 4,
    tags: ["grid", "capsule"],
    paths: [0, 2, 4, 6].flatMap((n) => [
      closedPath(`r${n}`, capsuleH(0, n, 6)),
      closedPath(`c${n}`, capsuleV(n, 0, 6)),
    ]),
  }),
  pattern({
    id: "nava",
    name: "Nava Kambi",
    gridSize: 7,
    category: "advanced",
    difficulty: 4,
    tags: ["rows", "capsule"],
    paths: [1, 3, 5].map((y) => closedPath(`r${y}`, capsuleH(1, y, 5))),
  }),
  pattern({
    id: "twin-maalai",
    name: "Twin Maalai",
    gridSize: 7,
    category: "advanced",
    difficulty: 4,
    tags: ["chain", "sikku"],
    paths: [
      closedPath("top", figureEightHorizontal({ x: 1, y: 2 })),
      closedPath("bottom", figureEightHorizontal({ x: 3, y: 4 })),
    ],
  }),
  pattern({
    id: "mahal",
    name: "Mahal",
    gridSize: 9,
    category: "advanced",
    difficulty: 5,
    tags: ["nested", "classic", "large"],
    paths: [
      closedPath("outer", enclosure(0, 0, 8, 8)),
      closedPath("mid", enclosure(2, 2, 6, 6)),
      ...moolaiSiluvai(5).map((points, i) => {
        const shifted = points.map((point) => ({ x: point.x + 2, y: point.y + 2 }));
        return closedPath(`inner-${i + 1}`, shifted);
      }),
    ],
  }),
  pattern({
    id: "brahma",
    name: "Brahma Mudi",
    gridSize: 9,
    category: "advanced",
    difficulty: 5,
    tags: ["complex", "plus", "frame"],
    paths: [
      closedPath("outer", enclosure(0, 0, 8, 8)),
      closedPath("h", capsuleH(1, 4, 7)),
      closedPath("v", capsuleV(4, 1, 7)),
      ...cornerLoops(9).map((points, i) => closedPath(`c${i + 1}`, points)),
    ],
  }),
];

export function listPatterns(): KolamPattern[] {
  return KOLAM_PATTERNS;
}

export function getPatternById(id: string): KolamPattern | undefined {
  return KOLAM_PATTERNS.find((patternItem) => patternItem.id === id);
}

export function patternsByCategory(category: KolamPattern["category"]): KolamPattern[] {
  return KOLAM_PATTERNS.filter((patternItem) => patternItem.category === category);
}

export function getTimedPool(): KolamPattern[] {
  return KOLAM_PATTERNS.filter((patternItem) => patternItem.difficulty <= 4).slice(0, 16);
}
